name: Auto Image Scraper Robot

on:
  schedule:
    - cron: '0 * * * *'
  workflow_dispatch:

jobs:
  scrape_images:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Force Install Colab Versions
      run: |
        pip install xlrd==1.2.0 Pillow google-api-python-client google-auth-httplib2 google-auth-oauthlib pandas openpyxl

    - name: Run the Scraper Robot
      run: python EXTRACTOR/image_scraper.py
